### ISSUE TITLE
Adding Files to a Project

### ISSUE THREAD

**Issue by brightproject** [wokwi/wokwi-features#641] opened 2023-08-28 07:18 UTC
@urish please relocate issue into https://github.com/wokwi/wokwi-features
I can't recover my Discord password - that's why I'm writing about problems here.
1. I simulate my project that runs on real hardware.

![photo1692643955 (2)](https://github.com/wokwi/wokwi-docs/assets/1788098/808c2d7d-5584-4f77-b675-c37222c197b1)

https://github.com/wokwi/wokwi-docs/assets/1788098/bb6748ee-96c4-4987-9396-8f1ecae9db82

Added 16 "*h" files and can't save project.
![Скриншот 27-08-2023 21 03 46](https://github.com/wokwi/wokwi-docs/assets/1788098/33a15540-3a43-4514-ac6e-e7b9f089d7d4)
Is this a limitation of the free version or a bug?
I managed to save the project archive - help me figure out why it is not saved and why the buttons do not always work adequately.
[Flightinstruments_TFT_eSPI.zip](https://github.com/GyverLibs/EncButton/files/12448649/Flightinstruments_TFT_eSPI.zip)
The project is quite interesting, and can greatly popularize your simulator.
In case of full adaptation of the code to the simulator, you can add it to the section [featured](https://wokwi.com/esp32) projects.
Please see it if possible.
Any questions are welcome.
3. Strange work with the button library [EncButton](https://github.com/GyverLibs/EncButton), the code compiles every other time.
[Issues](https://github.com/GyverLibs/EncButton/issues/42) with internal pullups, does the simulator not simulate internal pullups well?
4. The display
`"type": "board-ili9341-cap-touch"`
displays the image shifted to the right, you can see it in the screenshot above.
I wanted to [try](https://wokwi.com/projects/343960939576427090) another debug board, but I could not connect a display `ili9341` with the [TFT_eSPI](https://github.com/Bodmer/TFT_eSPI/) library, nor did I find examples - apparently it does not support these displays yet.
`"type": "board-esp32-s3-devkitc-1"`
As far as I understand, the simulator is not a 100% likeness of a real device, and you should not expect miracles from it.
There were thoughts to make a purchase, but the simulator did not work on the PC in [VS Code](https://docs.wokwi.com/vscode/getting-started), and there are still bugs in the online version.

**Comment by GyverLibs** [comment] 2023-08-29 13:44
Can't add the EncButton library with version newer than 2
### Wokwi
![image](https://github.com/wokwi/wokwi-docs/assets/84599917/e72b0447-8aec-4f9c-a9c9-62013c2faa5b)
### Arduino IDE
![image](https://github.com/wokwi/wokwi-docs/assets/84599917/e4ee73ab-d87b-492b-8b94-c585be926d85)
### Arduino registry
![image](https://github.com/wokwi/wokwi-docs/assets/84599917/531b6100-010b-4623-8a88-91ff6d170190)
### PlatformIO registry
![image](https://github.com/wokwi/wokwi-docs/assets/84599917/0d230268-180b-4d3a-8bb6-e87b99ead90a)

**Comment by urish** [comment] 2023-08-29 14:02
Thanks for reporting, will look into it

**Comment by urish** [comment] 2023-08-29 20:17
@GyverLibs should be fixed now, can you please try again?

**Comment by urish** [comment] 2023-08-29 20:38
Thanks for the feedback @brightproject!

1. I haven't had a chance to look at the project yet, but saving the project may fail if the total size of source code is greater than 1MB (only saved source code - not counting external libraries). This may happen if the .h file include large images.
3. We updated the libraries on the build server. Does it work more reliably now?
4. The image is not shifted to the right - the physical board has a black margin next to the display, so the simulation image also includes this margin. So this is by design. 
5. I'm curious - what issues are you having with the VS Code version?

**Comment by GyverLibs** [comment] 2023-08-29 20:46
@urish solved, thanks!

**Comment by brightproject** [comment] 2023-08-30 07:00
> 4\. I'm curious - what issues are you having with the VS Code version?

Thanks @urish for the replies.
In `VS Code` there is no possibility to edit the scheme visually, only in the file `diagram.json`
```
Simulation
ets Jul 29 2019 12:21:46
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1156
load:0x40078000,len:11456
ho 0 tail 12 room 4
load:0x40080400,len:2972
entry 0x400805dc
Flash size: 16777216 bytes
Psram size: 0 bytes
```
The speed of simulation execution is still very far from the speed of execution on a real microcontroller.
I tried to increase the flash memory and sdram, so if they realized the opportunity to increase the `SRAM` - the real esp32 `SRAM` has 512 kB.
Therefore, graphic displays work very fast.
Even a simple example works for me on [stm32f401](https://wokwi.com/projects/374062283976666113)

https://github.com/wokwi/wokwi-features/assets/1788098/da95c29d-d029-49bb-ac21-db0b7f8c8966

And in the simulator on `esp32` slows down.
Although ... there is still a nuance, in a real device - connection via an 8-bit interface is [parallel](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setups/Setup102_RP2040_ILI9341_parallel.h), and in a simulator via SPI.
Can I implement [fast SPI](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setups/Setup70b_ESP32_S3_ILI9341.h) in the simulator?
Perhaps you need to take `esp32-s3` for simulation?
Or does the simulation have one speed of operation for all microcontrollers?
It would also be possible to press two or more buttons at the same time.

**Closed as completed** 2023-11-07 11:09 UTC
