### ISSUE TITLE
'Start New project'

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#83] opened 2021-05-03 19:04 UTC
a request to have a "Start new project" option on the [homepage](https://wokwi.com).

**Comment by urish** [comment] 2021-05-04 16:43
Thanks for the suggestion! I plan to start working on it later this week 🤞

**Comment by urish** [comment] 2021-05-06 20:47
Duplicate of #21

**Closed by urish** 2021-05-06 20:47 UTC
Labels: duplicate, enhancement

**Comment by urish** [comment] 2021-05-06 20:49
https://wokwi.com/arduino/new

**Comment by Puneethkumarsn** [comment] 2021-05-07 09:20
Thanks 🥳
