### ISSUE TITLE
Turn " Sketch too big; Error during build: text section exceeds available space in board " error into warning if flash physical memory is not exceeded.  

### ISSUE THREAD

**Issue by DNbiss** [wokwi/wokwi-features#848] opened 2024-07-24 10:24 UTC
<!-- 

Considering that by using external programmers a sketch can occupy all the flash memory, it is necessary that the error "Sketch too big; " to be turned into a warning if physical memory is not exceeded, so as not to limit the options for loading sketches.
Example: Arduino NANO 328p has 32768 bytes flash memory that is limited to 30720 bytes when using bootloader.
By using optiboot_atmega328.hex and modifying the "boards.txt" file Arduino IDE, even with bootloader you can use 32256 bytes flash memory on NANO.
I think it can be done simply, through a Wokwi setting option, creating the advantage of loading sketches that exceed 30720 bytes in the case of NANO.
This proposal addressed to Wokwi developers helps users who use a lot of text or very large sketches.
Also, as proposed, it would be useful to display how much FLASH/RAM memory is used after compilation. 
Thanks for understanding.

**Comment by sutaburosu** [comment] 2024-07-24 10:36
~Can you please provide an example of a sketch which generates this error, but the generated binary is smaller than the available Flash memory.~

I've just seen your update on #849. This issue seems to be a duplicate of that, so perhaps you could close this issue.

**Comment by DNbiss** [comment] 2024-07-24 10:50
On Wednesday, July 24, 2024 at 01:37:14 PM GMT+3, sutaburosu ***@***.***> wrote:  
 
 


Can you please provide an example of a sketch which generates this error, but the generated binary is smaller than the available Flash memory.

—
Reply to this email directly, view it on GitHub, or unsubscribe.

Primiți acest lucru deoarece ați fost autorul firului.


This is the sketch.
https://wokwi.com/projects/404202709055278081

**Closed as completed** 2024-07-28 13:24 UTC
Labels: enhancement
