### ISSUE TITLE
RFID READ

### ISSUE THREAD

**Issue by QUANGQUY1305** [wokwi/wokwi-features#455] opened 2022-11-20 08:38 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by urish** [comment] 2022-11-20 11:40
Do you mean an [MFRC522](https://www.nxp.com/docs/en/data-sheet/MFRC522.pdf) reader, like this one?

![image](https://user-images.githubusercontent.com/892318/202899972-f061b763-5a6c-4e99-9b5e-5d7519855858.png)

**Comment by urish** [comment] 2023-03-04 08:02
Duplicate of #359

**Closed as completed by urish** 2023-03-04 08:02 UTC
Labels: enhancement
