### ISSUE TITLE
IDE (VSCode) Integration

### ISSUE THREAD

**Issue by Twistx77** [wokwi/wokwi-features#414] opened 2022-09-10 16:58 UTC
For many people that wants to use Wokwi for a bit more complex projects, working on the browser is less than ideal. I think that instead of reinventing the wheel making a full fledged editor on the browser, a better solution would be to implement some kind of plugging for VSCode or any other IDE or at least an API that would allow to upload the compiled binary file to Wokwi and run the simulation. With the API anyone (Me for example) could create a simple script that could upload the binary and run it. 

This would also be a solution for this feature request, which would not be needed in most cases[Github integration](https://github.com/wokwi/wokwi-features/issues/75#top)
wokwi/rp2040js#75

**Comment by urish** [comment] 2022-09-10 17:11
Thanks for the feature request! I opened it for [voting](https://wokwi.com/features?sort=newest#feature-1368676003).

**Comment by urish** [comment] 2022-11-20 21:49
Good news - we have a prototype version!

https://user-images.githubusercontent.com/892318/202927900-737a5530-9d26-4fef-87a6-6c06a80b5444.mp4

If you want early access, please ping me on [discord](https://wokwi.com/discord).

**Comment by Twistx77** [comment] 2022-11-21 05:27
Bravo!! 👏

This is awesome! This will avoid having to upload the code, solves the keeping repositories up to date etc.

We can work now as with the real device and choose to run it on Wokwi or directly program the real device id available.

Hopefully the debugger can be used throu VSCode in the future and would it make it perfect. I'm glad that I'm supporting the project.

I will try it as soon as I have time.

Thank you!

**Comment by leon0399** [comment] 2022-11-24 11:44
Wow! Impressive work! I'm wondering if the same implementation can be integrated into PlatformIO for simulation.
https://docs.platformio.org/en/latest/advanced/unit-testing/simulators/index.html

**Comment by urish** [comment] 2022-11-24 11:46
Thank you @leon0399! Are you using Platform IO from Visual Studio Code or from command line?

**Comment by leon0399** [comment] 2022-11-24 12:10
> Thank you @leon0399! Are you using Platform IO from Visual Studio Code or from command line?

Both! 😄 
Using in VSCode for development and CLI for scripts and CI

**Comment by urish** [comment] 2022-11-24 12:12
Got it! You can get early access to the VSCode plugin - just ping me on discord. It should work with Platform IO projects (there are even some examples, e.g. [this one](https://github.com/wokwi/arduino-simon-game))

**Comment by ricardojlrufino** [comment] 2022-11-27 05:05
wow, amazing.

**Comment by steve-barth** [comment] 2022-11-29 14:46
Thanks Uri!

**Comment by urish** [comment] 2023-01-15 16:23
Wokwi for VS Code is now in public beta: https://marketplace.visualstudio.com/items?itemName=wokwi.wokwi-vscode

Docs: https://docs.wokwi.com/vscode/getting-started

If you love it, a 5-star rating in the VS Code marketplace would be helpful (but if you don't think it deserves 5 stars, please leave a comment here so we know why). Thanks :)

**Comment by Twistx77** [comment] 2023-01-15 20:16
Done :)

**Comment by forntoh** [comment] 2023-01-27 10:39
Can't install on vscode version 1.70.0

**Comment by urish** [comment] 2023-01-27 10:44
> Can't install on vscode version 1.70.0

What do you see when you are trying to install? Can you please share a screen shot?

**Comment by forntoh** [comment] 2023-01-27 10:57
![image](https://user-images.githubusercontent.com/27886627/215069991-703bc5a1-5c5a-4bc8-a617-b5aba63e717d.png)

**Comment by urish** [comment] 2023-01-27 10:58
Thanks @forntoh! What stops you for updating to the latest VS Code version (1.74.3)?

**Comment by forntoh** [comment] 2023-01-27 11:02
> Thanks @forntoh! What stops you for updating to the latest VS Code version (1.74.3)?

I don't know why I can't update, I don't even see the command to update nor do I find it in the help menu. I'll try again.

**Comment by urish** [comment] 2023-01-27 11:04
It is usually here:

![image](https://user-images.githubusercontent.com/892318/215071368-9c7ac5a4-8e5d-49a0-b577-6ae2df2c2cc9.png)

**Comment by forntoh** [comment] 2023-01-27 11:05
I don't have that menu item on mine 😄 why?
![image](https://user-images.githubusercontent.com/27886627/215071592-1fa2eab3-3c7e-4c00-8167-51fabc423d4a.png)

**Comment by urish** [comment] 2023-01-27 11:07
Seems it could be related to microsoft/vscode#157383 - where it stopped auto-updating after version 1.70.0. I think the easiest fix is just to download and install the latest version from [the website](https://code.visualstudio.com/Download)

**Comment by forntoh** [comment] 2023-01-27 11:12
> Seems it could be related to [microsoft/vscode#157383](https://github.com/microsoft/vscode/issues/157383) - where it stopped auto-updating after version 1.70.0. I think the easiest fix is just to download and install the latest version from [the website](https://code.visualstudio.com/Download)

Thanks, I found a solution, yeah it's actually related to [vscode#157383](https://github.com/microsoft/vscode/issues/157383) and [vscode#147408](https://github.com/microsoft/vscode/issues/147408)

**Comment by alextrical** [comment] 2023-02-13 19:27
I have noticed that the simulation in the Visual studio environment is a bit blurred, and makes screens difficult to use.
Is this a known bug, or an issue with my setup on Ubuntu?
![image](https://user-images.githubusercontent.com/35117191/218554707-d0eebd11-a60b-43be-ae7e-7d27a734e2a6.png)
Visual Studio Code on left, web version in Firefox on the right

**Comment by urish** [comment] 2023-02-13 19:38
a "bit blurred" is an understatement. The OLED screen is barely usable! 

I haven't seen this issue before. Does it always happen? Which VS Code/ubuntu version?
Does Chrome or Chromium have a similar issue?

**Comment by alextrical** [comment] 2023-02-13 20:04
It seems as if the anti-aliasing is set at the time the simulation is first loaded, and the zoom just increases the pixel size, without recalculating the 'smoothing'. 

Though as a work around it seems that if zoomed in enough, visual studio readjusts the image to be readable once zoomed back out
![image](https://user-images.githubusercontent.com/35117191/218562936-47a65e90-9510-43f4-bc91-e2857d032134.png)



Current setup is:
Visual studio Code 1.75.1 installed via Snap
KUbuntu 22.10
x11 desktop system. Will try Wayland to see if that makes a difference
Asus UX410U with 20GB Ram

Chromium does indeed have a bit of an issue, but its definitely useable
![image](https://user-images.githubusercontent.com/35117191/218562591-20781fa7-3304-4b0d-a1d6-d5feec325335.png)

**Comment by urish** [comment] 2023-02-13 20:07
> It seems as if the anti-aliasing is set at the time the simulation is first loaded, and the zoom just increases the pixel size, without recalculating the 'smoothing'. Though it seems that if zoomed in enough it does readjust the image to re readable once zoomed back out

Yes, I've seen this happening with Chrome. I guess it's some sort of optimization that it does to speed up drawing. But never to the degree that you are showing with VS Code. I'll see if I can reproduce it here.

**Comment by alextrical** [comment] 2023-02-13 20:53
https://user-images.githubusercontent.com/35117191/218571618-07228cb8-16a8-4f31-bd71-e14d2eba2cb0.mp4

I will keep an eye out for a fix, as i think this is an issue with my setup and Visual Studio code. If i find a solution to disable the anti-aliasing I will let you know :)
Its not a major issue (and by the sounds of it only effecting me), so I would say don't waste too much time looking into it.

**Comment by realJoshByrnes** [comment] 2023-03-08 18:39
Referencing an issue I'm having using the VSCode extension: https://github.com/wokwi/wokwi-features/issues/545

**Comment by loopj** [comment] 2023-06-07 17:36
@alextrical I'm also seeing this exact blurring issue in VSCode, on a mac

**Comment by alextrical** [comment] 2023-06-07 19:58
@loopj In a way I'm glad that there is another instance of this happening on another OS, it will hopefully allow the bug to be tracked down and resolved. :)

**Comment by pe5er** [comment] 2023-12-05 15:28
> I have noticed that the simulation in the Visual studio environment is a bit blurred, and makes screens difficult to use. Is this a known bug, or an issue with my setup on Ubuntu? ![image](https://user-images.githubusercontent.com/35117191/218554707-d0eebd11-a60b-43be-ae7e-7d27a734e2a6.png) Visual Studio Code on left, web version in Firefox on the right

I am also having this issue on Windows 11. Other than that, the VSCode Integration is a beast!

**Comment by FiveTeethless** [comment] 2023-12-12 21:40
same here on Windows 11 and VSCode 1.85.0
Chromium is of version 114.0.5735
Let me know, how I can help finding this issue.

Sometimes it renders the view very sharp after some time and fiddeling, but I couldn't find some definitive conditions for it.

**Comment by pe5er** [comment] 2023-12-12 23:29
I found that instead of fixing it by zooming in really far, I could fix it by clicking on the vs code interface outside of the Wokwi simulator, pressing control+ = to zoom in, then control+ - to zoom out. 

This works regardless of how zoomed in the Wokwi simulator itself is.

Hopefully that provides a clue, but failing that it's an easier workaround

**Comment by urish** [comment] 2023-12-17 10:38
Thanks for sharing your workaround @pe5er! I hope I'll be able to reproduce this in a consistent way and then find a solution.

**Comment by urish** [comment] 2023-12-27 21:35
Closing this issue, as Wokwi for VS Code is now out of beta. Feel free to open new issues for any bugs or feature requests related to Wokwi for VS Code.

**Closed as completed by urish** 2023-12-27 21:35 UTC
Labels: enhancement, open for vote

**Comment by urish** [comment] 2024-03-17 11:09
> I found that instead of fixing it by zooming in really far, I could fix it by clicking on the vs code interface outside of the Wokwi simulator, pressing control+ = to zoom in, then control+ - to zoom out.

Good news: I managed to reproduce this, and uploaded a fix that works for me.

@pe5er /  @FiveTeethless / @alextrical / @loopj can you please check if blurring still happens for you?

**Comment by pe5er** [comment] 2024-03-18 09:07
@urish seems fixed for me - thanks for your help!

**Comment by alextrical** [comment] 2024-03-18 15:09
@urish same here, looks good this end too. Thank you so much

**Comment by FiveTeethless** [comment] 2024-03-20 22:10
> > I found that instead of fixing it by zooming in really far, I could fix it by clicking on the vs code interface outside of the Wokwi simulator, pressing control+ = to zoom in, then control+ - to zoom out.
> 
> Good news: I managed to reproduce this, and uploaded a fix that works for me.
> 
> @pe5er / @FiveTeethless / @alextrical / @loopj can you please check if blurring still happens for you?

thanks, also works on my machine! 👍

**Comment by ShakaAmilcar876** [comment] 2024-05-07 02:11
> I have noticed that the simulation in the Visual studio environment is a bit blurred, and makes screens difficult to use. Is this a known bug, or an issue with my setup on Ubuntu? ![image](https://user-images.githubusercontent.com/35117191/218554707-d0eebd11-a60b-43be-ae7e-7d27a734e2a6.png) Visual Studio Code on left, web version in Firefox on the right

How do you run custom chips in VSCode? Where do you go to find the 'wokwi_api.h' header file??

**Comment by urish** [comment] 2024-05-12 08:25
> How do you run custom chips in VSCode? Where do you go to find the 'wokwi_api.h' header file??

You can find an example on https://github.com/wokwi/inverter-chip/tree/main/src

Please use the [Wokwi community chat on Discord](https://wokwi.com/discord) for questions.
