### ISSUE TITLE
After compilation, indicate the mmemory usage as on Arduino IDE

### ISSUE THREAD

**Issue by Aldec60** [wokwi/wokwi-features#772] opened 2024-04-24 10:31 UTC
I don't know if is just a mistake from myself or an unavailable feature, but it could be interesting to see the memory usage as result of the compilation.

Thank you !

**Comment by Noah13s** [comment] 2024-04-30 08:33
+1

**Comment by urish** [comment] 2024-04-30 10:57
Thanks for the suggestion - this is actually a duplicate of #1

**Closed as completed by urish** 2024-04-30 10:57 UTC
Labels: duplicate, enhancement
