### ISSUE TITLE
Button release doesn't work properly

### ISSUE THREAD

**Issue by kontiko** [wokwi/wokwi-features#578] opened 2023-05-16 18:15 UTC
**Describe the bug**
Button doesn't release when Mouse is moved from Button

**To Reproduce**
Press on Button and hold it.
Move Mouse away from Button.
Release Mouse Button.
Button is still active

**Expected behavior**
Button releases even when Mouse moved

**Environment (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 113.0

**Comment by urish** [comment] 2023-05-21 09:58
This started as a bug, but AFAIK some users are now using it as an "undocumented feature" to hold multiple buttons at a time. Not sure if we should fix it - I'll post this issue to the [Wokwi discord chat](https://wokwi.com/discord) to get more opinions.

**Comment by urish** [comment] 2023-05-21 10:00
Note that there's also a documented keyboard shortcut to achieve the same functionality: https://docs.wokwi.com/parts/wokwi-pushbutton#stickiness

**Comment by Vollbrecht** [comment] 2023-05-21 12:09
I personally think than it should be fixed. And for the people who needed that functionality. They should either using a dip switch - or you could add an option to the button itself  - to make it a latching button.  For a speed-runner its not nice if you fix a glitch but for a normal player the overall experience is more important. And i think serving the normal player here is the right call.
I think one root of the problem is that the people didn't discover the latching option. So i think it would be nice if you add it directly as a toggle option here:
 
![Screenshot from 2023-05-21 14-05-26](https://github.com/wokwi/wokwi-features/assets/12041081/08db459b-ba05-46bb-82e6-8512e2f995e4)

And maybe calling it a latching button and not a sticky one :smile_cat: Though i admit it is a bit funny.

**Comment by AriellaE** [comment] 2023-06-29 09:22
Hello @kontiko 
I fixed this bug. 
Thank you very much!

**Closed as completed by AriellaE** 2023-06-29 09:22 UTC
Labels: bug
