### ISSUE TITLE
Wiring issue - wire is away from the mouse cursor

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#138] opened 2021-07-06 12:55 UTC
I observed the starting point of the wire to be off from the mouse pointer edge. 
The issue appeared in between. Earlier the wires were being drawn properly. once I deleted two wires and then tried to redraw the issue appeared. The screenshot is attached. Notice how soon after connecting the wire to Pin number one, the tip of the wire snatched back to the LED anode (rightmost). while moving the mouse, the wire stays a few lengths away. it happens to all the pions once it starts. 

The issues goes if I save the project/reload the project
![scroll rightw](https://user-images.githubusercontent.com/68117142/124603072-2d7c3c80-de87-11eb-94d8-11b9eb97119a.gif)

**Comment by urish** [comment] 2021-07-06 16:06
Is it related to zooming / panning the diagram? A list of steps to reproduce will be very helpful!

**Comment by urish** [comment] 2021-09-16 20:03
Closing as I couldn't reproduce it. Feel free to reopen if you find a consistent way of reproducing the issue.

**Closed by urish** 2021-09-16 20:03 UTC
Labels: bug
