### ISSUE TITLE
rfid reader

### ISSUE THREAD

**Issue by glitchplaysgames714** [wokwi/wokwi-features#643] opened 2023-09-07 00:58 UTC
include a rfid reader object based on the Mifare RC522 module that can be found [here](https://www.amazon.com/HiLetgo-RFID-Kit-Arduino-Raspberry/dp/B01CSTW0IA/ref=sr_1_5?crid=1PS0G1YK21LKM&keywords=mifare+rfid+module&qid=1694048179&sprefix=mifiare+rfid+modul%2Caps%2C483&sr=8-5)

there would also be a rfid card object that when moved infront of the reader simulates what would happen when you create the object it has a random hex but you can edit it in the simulation

**Comment by urish** [comment] 2023-09-18 15:18
Closing, this is a duplicate of #359

**Closed as completed by urish** 2023-09-18 15:18 UTC
Labels: duplicate, enhancement

**Comment by AbdennourBELKACEM** [comment] 2024-11-05 15:30
please include a rfid reader object based on the Mifare RC522 module, then community is in need for this module in the simulator

**Comment by djedu28** [comment] 2024-11-05 22:37
@AbdennourBELKACEM

1. Before commenting, check previous comments.
- This issue was closed because it's a duplicate of https://github.com/wokwi/wokwi-features/issues/359

2. You can build your own CI Mifare RC522
- https://docs.wokwi.com/chips-api/getting-started

3. As an alternative to RC522, I made my own RDM6300 CHIP, you can use it

- In the past I had the need to emulate an RFID reader, and I did a basic simulation of the [RDM6300 Chip](https://github.com/djedu28/wokwi-rdm6300-custom-chip) <https://github.com/djedu28/wokwi-rdm6300-custom-chip>
![image](https://github.com/user-attachments/assets/1b3b756a-39f6-489d-a54a-e53e4505f77c)

## diagram.json
```json
{
  "version": 1,
  "author": "Edu Santos",
  "editor": "wokwi",
  "parts": [
    { "type": "wokwi-arduino-uno", "id": "uno1", "top": 0.6, "left": -0.6, "attrs": {} },
    { "type": "chip-rdm6300", "id": "chip1", "top": 97.02, "left": 302.4, "attrs": {} }
  ],
  "connections": [
    [ "chip1:VCC", "uno1:5V", "red", [ "h-28.8", "v115.2", "h-86.4" ] ],
    [ "chip1:GND", "uno1:GND.2", "black", [ "h-19.2", "v124.8", "h-115.2" ] ],
    [ "chip1:RX", "uno1:1", "gold", [ "v0", "h30.61", "v-153.6", "h-192" ] ],
    [ "chip1:TX", "uno1:0", "green", [ "h11.41", "v-124.8", "h-166.9" ] ]
  ],
  "dependencies": { "chip-rdm6300": "github:djedu28/wokwi-rdm6300-custom-chip@0.28.2" }
}
```
---- 

> 1. Antes de comentar, verifique os comentários anteriores.
> - Este issues foi fechado por ser uma duplicata de https://github.com/wokwi/wokwi-features/issues/359
> 
> 2. Você pode construir seu próprio CI Mifare RC522
> - https://docs.wokwi.com/chips-api/getting-started
> 
> 3. Como alternativa ao RC522, fiz o meu próprio CHIP RDM6300, você pode usá-lo
> 
> - No passado tive a necessidade de emular um leitor de RFID, e fiz uma simulação básica do [RDM6300 Chip ](https://github.com/djedu28/wokwi-rdm6300-custom-chip)  <https://github.com/djedu28/wokwi-rdm6300-custom-chip>
> ![image](https://github.com/user-attachments/assets/1b3b756a-39f6-489d-a54a-e53e4505f77c)
>

**Comment by anton21m** [comment] 2025-07-17 18:17
I DID IT! 🎉

After 4 weeks of sleepless nights and deep dives into low-level emulation…
The RC522 chip is now fully simulated in Wokwi! 🧠⚡

✅ The MFRC522 Arduino library is now working right in the browser
✅ You can even connect multiple RFID readers with unique UIDs
✅ Works seamlessly with real Arduino code and examples

Try it yourself:

🔬 Full MFRC522 test project:
👉 https://wokwi.com/projects/432456562791073793

📚 Multiple readers with unique UIDs:
👉 https://wokwi.com/projects/436744920653539329

📦 Chip export demo:
👉 https://wokwi.com/projects/436746939600791553

Found a bug? Have ideas?
Create an issue here:
🐞 https://github.com/anton21m/wokwi-rc522-rfid-chip

Let’s build the future of virtual electronics together 🚀

**Comment by djedu28** [comment] 2025-08-04 13:19
Congratulations! @anton21m  

I recommend publishing in #359 (which is the issue being tracked for this hardware)

**Comment by glitchplaysgames714** [comment] 2025-08-05 00:07
i have no recollection of making this post ToT

**Comment by urish** [comment] 2026-02-02 19:20
Good news: the MRFC522 is now officially supported on Wokwi!

Docs: https://docs.wokwi.com/parts/board-mfrc522
Example project: https://wokwi.com/projects/454873133691473921
