### ISSUE TITLE
Serial Monitor no loger working when running under firefox

### ISSUE THREAD

**Issue by ithinkido** [wokwi/wokwi-features#140] opened 2021-07-06 15:41 UTC
I was using wokwi a week ago, and everthing was great. Today, I have no serial monitor ( well , just a blank window) when using Wokwi under Firefox. The same sketch works fine under Edge.
https://wokwi.com/arduino/projects/303380952077304386

![image](https://user-images.githubusercontent.com/52834821/124629108-69ac9e80-de81-11eb-81f8-9ae633c1b18c.png)

**Comment by urish** [comment] 2021-07-06 15:45
This reproduces here

**Comment by urish** [comment] 2021-07-06 16:01
Seems to be related to the recent changes from #130 (allowing the serial terminal to be resized)

**Comment by urish** [comment] 2021-07-06 16:03
Should be fixed now

**Closed by urish** 2021-07-06 16:03 UTC
Labels: bug

**Comment by ithinkido** [comment] 2021-07-06 16:26
That was fast, yes it , thanks
